version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1
  nx: nrwl/nx@1.6.0

jobs:
  setup:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package-lock.json" }}
      - continuation/continue:
          configuration_path: ./.circleci/continuation.yml

workflows:
  setup:
    jobs:
      - setup
