version: 2.1

parameters:
  affected-projects-build:
    type: string
    default: ''
  num-affected-projects-build:
    type: integer
    default: 1

jobs:
  build:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Build affected projects
          command: |
            AFFECTED_PROJECTS=$(echo "<<pipeline.parameters.affected-projects-build>>") | sed 's/, /\n/g' | circleci tests split)
            npx nx run-many --target=build --projects=$AFFECTED_PROJECTS

  lint:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ checksum "package-lock.json" }}
      - run:
          command: echo "lint completed"

  test:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ checksum "package-lock.json" }}
      - run:
          command: echo "test completed"

workflows:
  build-lint-test:
    jobs:
      - build
      - lint
      - test
